### ISSUE TITLE
Assessment Results

### ISSUE THREAD

**Issue by rwarbelow** [kaylalarson1990/mod_0_skills#1]
# Checklist/Rubric

#### Part I: Creating Directories and Files; Initializing Git and Pushing to GitHub
* [x]  Directories are named correctly.
* [x]  Files are named correctly.
* [x]  Files and directories are structured correctly.
* [x]  Initial commit was made.
* [x]  Initial commit was pushed to GitHub.

#### Part II: Top Down Design
* [x]  Larger processes were broken into smaller layers.
* [x]  Changes were added and committed with a properly formatted commit message starting with a verb and a capital letter.
> Somehow a commit with the message `first commit` snuck in between your initial commit and the one for breaking down the food ordering process 🤔 
* [x]  Changes were pushed to Github.

#### Part III: Classes in a System
* [x]  Directories and files were named and structured correctly.
* [ ]  The attributes chosen for **Class #1** represent states or characteristics.
> `foodOptions`, `drinkOptions`, and `cateringOptions` are all correct attributes of a `Menu` class. For `price` and `calories`, those would be attributes of an `Item` class (since a menu itself doesn't have a price or calories -- that would be like buying and eating the menu!) When you think about the attributes, make sure that they are applicable to any object.  I like to ask, "Can [object] have a / be [attribute]?"
> For example:
* "Can a menu have foodOptions?" (yes)
* "Can a menu have a drinkOptions?" (yes)
* "Can a menu have a price?" (no, but **items** on the menu can have a price)
* "Can a menu have calories?" (no, but **items** on the menu can have calories)

* [ ]  The attributes chosen for **Class #2** represent states or characteristics.
> I'm confused by the `Sign In` class. Think of classes as nouns that have clearly defined attributes and methods/behaviors: `Customer`, `Order`, `Item`, `Furniture`, `Server`, etc. Generally, these map to real-life objects. While a sign in section would appear in a food-ordering app, it probably wouldn't be an object (and is hard to map to something in real life). 

* [ ]  The attributes chosen for **Class #3** represent states or characteristics.
> `username`, `comments`, and `datePosted` are great attributes for a review. `Like/dislike a comment` would be a method on a `Comment` class since we can't ask the question "Can a Review have a `Like/dislike a comment?`" (no/confusing)

* [ ]  The methods chosen for **Class #1** represent behaviors or actions.
> The methods listed here seem to be more fit for an `Order` class. For `Menu`, methods might be things like `addItem`, `removeItem`, `changeServiceFee`, `updateCategories`, etc. 

* [ ]  The methods chosen for **Class #2** represent behaviors or actions.
> See above notes for Class #2. 
* [ ]  The methods chosen for **Class #3** represent behaviors or actions.
> You're on the right track with your thinking for how comments and reviews might interact. In this case, I might include one method `addNewComment`. For the other methods (`deleteComment` and `RespondToComment`), those would be methods I would include on a `Comment` class. 

* [x]  Data type (string, integer, boolean, array, hash/object, datetime) were identified for each attribute in all three classes.
* [x]  Individual changes were added and committed separately with a properly formatted commit message.
* [x]  Changes were pushed to Github.

**Mod 0 Technical Assessment Results**

* [ ]   Technical Ready
* [x]   Pending
> Next steps: Clean up `class_1.txt` and `class_3.txt` using the feedback. Choose a different class for `class_2.txt` (you can use anything from the suggestions above) and list the attributes and methods. 
* [ ]   Not Ready

**Comment by rwarbelow** [comment]
Changes look good!

- [x] Technical Ready
